name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install correct error_highlight version
        run: gem install error_highlight -v 0.7.0

      - name: Update Bundler and resolve dependencies
        run: |
          gem install bundler -v $(grep -A1 'BUNDLED WITH' Gemfile.lock | tail -n1)
          bundle install

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager

  scan_js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install correct error_highlight version
        run: gem install error_highlight -v 0.7.0

      - name: Update Bundler and resolve dependencies
        run: |
          gem install bundler -v $(grep -A1 'BUNDLED WITH' Gemfile.lock | tail -n1)
          bundle config set frozen false
          bundle update error_highlight
          bundle install

      - name: Scan for security vulnerabilities in JavaScript dependencies
        run: bin/importmap audit

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install correct error_highlight version
        run: gem install error_highlight -v 0.7.0

      - name: Update Bundler and resolve dependencies
        run: |
          gem install bundler -v $(grep -A1 'BUNDLED WITH' Gemfile.lock | tail -n1)
          bundle update error_highlight
          bundle install

      - name: Lint code for consistent style
        run: bin/rubocop -f github

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y google-chrome-stable curl libjemalloc2 libvips sqlite3

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install correct error_highlight version
        run: gem install error_highlight -v 0.7.0

      - name: Update Bundler and resolve dependencies
        run: |
          gem install bundler -v $(grep -A1 'BUNDLED WITH' Gemfile.lock | tail -n1)
          bundle update error_highlight
          bundle install

      - name: Run tests
        env:
          RAILS_ENV: test
        run: bin/rails db:test:prepare test test:system

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore
